apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "trino.fullname" . }}-istio-virtual-service
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
spec:
  hosts:
    - "{{ .Release.Name }}.hadoop.{{ .Values.server.node.environment }}.6si.com"
  gateways:
    - istio-system/http-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: "{{ .Release.Name }}.{{ .Release.Name }}.svc.cluster.local"
            port:
              number: 8080
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx
